created updated for profiles pref
GenerateNU/nightlife pull request #33
Opened 2024-09-28 21:24 UTC by kaamil2

<img width="908" alt="Screenshot 2024-09-28 at 5 23 29 PM" src="https://github.com/user-attachments/assets/2e0a9901-48b3-4a06-9598-1dae46c28294">
<img width="638" alt="Screenshot 2024-09-28 at 5 23 26 PM" src="https://github.com/user-attachments/assets/c80e8a2d-8771-400f-93b4-f916dce2e954">
# Description

[Link to Ticket](insert the link to your ticket inside the parenthesis here)

Please include a summary of the changes and the related issue. Please also
include relevant motivation, context, and images!

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. If they are unit
tests, provide the file name the tests are in. If they are not unit tests,
describe how you tested the change.

# Checklist

- [ ] I have performed a self-review of my code
- [ ] I have reached out to another developer to review my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes

2024-09-29 23:58 UTC, CamPlume1 approved these changes
Looks really great

2024-09-29 23:59 UTC, CamPlume1 requested changes

2024-09-29 23:59 UTC, CamPlume1 commented on backend/internal/types/params.go
> +	UserID            uuid.UUID `json:"user_id"`
This should be in models not types

2024-09-30 00:05 UTC, kaamil2 commented on backend/internal/types/params.go
> +	UserID            uuid.UUID `json:"user_id"`
think this is good now

2024-09-30 00:15 UTC, CamPlume1 approved these changes

2024-09-30 16:27 UTC, CamPlume1 requested changes

2024-09-30 16:27 UTC, CamPlume1 commented on backend/internal/storage/storage.go
> +	UpdateProfilePrefences(context.Context, uuid.UUID, string, string, string, string) error
This should be combined with the Profile interface, as they cover the same db table

2024-10-22 23:18 UTC, closed without merging