Feature/delete/venue review
GenerateNU/nightlife pull request #34
Opened 2024-09-30 01:01 UTC by abyan-n

# Description

[Link to Ticket](insert the link to your ticket inside the parenthesis here)

Please include a summary of the changes and the related issue. Please also
include relevant motivation, context, and images!
https://trello.com/c/H37iULmB/19-delete-api-venues-reviews-reviewid

Added a delete endpoint to delete a review for a venue.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. If they are unit
tests, provide the file name the tests are in. If they are not unit tests,
describe how you tested the change.

Postman, checked with valid ID, invalid ID, invalid path params.

# Checklist

- [X ] I have performed a self-review of my code
- [ ] I have reached out to another developer to review my code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] New and existing unit tests pass locally with my changes

2024-09-30 02:19 UTC, CamPlume1 requested changes
Small notes:

1. Combine Interface is the blocking change here. Deleting legacy comment would be a nice bonus 👍

2024-09-30 02:19 UTC, CamPlume1 commented on backend/internal/handlers/venues/routes.go
> +//NOTE: This is an example usage for auth demonstration purposes. In real configurations (beyond login) all route groups should be protected
Probably delete legacy comments

2024-09-30 02:19 UTC, CamPlume1 commented on backend/internal/storage/storage.go
> +type Venues interface {
I think we should combine Venue and Venue Ratings interfaces. IMO they provide functionality over the same data structure and belong together

2024-10-01 17:02 UTC, wyattchris reviewed
interface change resolved

2024-10-01 17:02 UTC, wyattchris commented on backend/internal/storage/storage.go
> +type Venues interface {
looks great!!

2024-10-01 17:10 UTC, merged