Feature/venue backend - Event Table connected
GenerateNU/nightlife pull request #73
Opened 2024-11-11 00:50 UTC by ihysi2024

Connected event scroll bar to backend

2024-11-13 20:14 UTC, garrettladley requested changes

2024-11-13 20:14 UTC, garrettladley commented on backend/internal/models/event.go
> +	Date      time.Time `json:"event_date"`
having an `Event.Date` of type `time.Time` and an `Event.Time` of type `time.Time` is redundant

2024-11-13 20:14 UTC, garrettladley commented on backend/internal/models/event.go
> +	return nil
- [ ] fill out this stub. probably want simple checks on string len of [name, image path], etc etc based on requirements

2024-11-13 20:14 UTC, garrettladley commented on backend/internal/utils/validators.go
> +	var emailRegex = regexp.MustCompile(`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`)
these regex are being compiled on each function call. they should be precompiled in a private var, then used in this function

2024-11-13 20:14 UTC, garrettladley commented on backend/internal/utils/validators.go
> +func IsUUID(input string) bool {
use `uuid.Parse` instead.

```go
var raw string
// populate raw somehow
uuid, err := uuid.Parse(raw)
if err != nil {
// !valid, handle me
}
```

2024-11-13 20:14 UTC, garrettladley commented on Makefile
> +<<<<<<< HEAD
finish resolving this merge conflict?

2024-11-13 20:14 UTC, garrettladley commented on Makefile
> +=======
finish resolving this merge conflict?

2024-11-13 20:14 UTC, garrettladley commented on Makefile
> +>>>>>>> b6136ca773a9f06b8b6704803b38115da574bbaa
finish resolving this merge conflict?

2024-11-15 14:22 UTC, CamPlume1 approved these changes

2024-11-25 21:26 UTC, CamPlume1 commented
Closing after checking in with Ira

2024-11-25 21:28 UTC, closed without merging